TARGET = server
#UTILS = ../utils/MapUtils.cpp
UTILSINC = ../utils/MapUtils.h ../utils/Log.h
SOURCES  = $(wildcard *.cpp ./gen-cpp/*.cpp) $(UTILS)
INCLUDES = $(wildcard *.h gen-cpp/*.h) $(UTILSINC)

include ../Makefile.inc

